spring:
  elasticsearch:
    uris: http://elasticsearch:9200
  kafka:
    bootstrap-servers: kafka:9094
    consumer:
      group-id: search-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "tuantha8203.*"
        spring.json.type.mapping: >-
          productCreated:tuantha8203.searchservice.events.ProductCreatedEvent,
          productUpdated:tuantha8203.searchservice.events.ProductUpdatedEvent,
          productDeleted:tuantha8203.searchservice.events.ProductDeletedEvent